{% set version = "2.34.1" %}

package:
  name: magics
  version: {{ version }}

source:
  fn: Magics-{{ version }}-Source.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473464/Magics-{{ version }}-Source.tar.gz
  sha256: 8df27f8f262ebc32a61f8696df15a7b4a6e4203b2a8e53fe7aa13caa1c4e3fa4

build:
  number: 0
  skip: True  # [win or not py27]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - swig
    - pkgconfig
    - boost 1.64.*
    - glib
    - pango 1.40.*
    - proj4 4.9.3
    - python-eccodes
    - python
    - perl 5.22.2.1
    - perl-xml-parser
    # ecBuild fails to find the C++ bindings: the library name is libnetcdf_c++4
    # - netcdf-cxx4
  run:
    - pango 1.40.*
    - proj4 4.9.3
    - python-eccodes
    - python
    - simplejson
    # ecBuild fails to find the C++ bindings: the library name is libnetcdf_c++4
    # - netcdf-cxx4

test:
  commands:
    - conda inspect linkages -p $PREFIX magics  # [not win]
    - conda inspect objects -p $PREFIX magics  # [osx]
  imports:
    - Magics
    - Magics.macro
    - Magics.metgram
    - Magics.toolbox

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF's Meteorological plotting software

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
