{% set version = "3.2.1" %}

package:
  name: magics
  version: {{ version }}

source:
  fn: Magics-{{ version }}-Source.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473464/Magics-{{ version }}-Source.tar.gz
  sha256: da5f95b03e5e175e1886cc14dc45eab39af76bb2f0e40e2c20192b0683cd23e6

build:
  number: 2
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - pkgconfig
    - expat 2.2.*
    - glib
    - pango 1.40.*
    - proj4 4.9.3
    - eccodes
    - python
    - numpy 1.8.*
    - jinja2
    - libnetcdf
    - zlib
  run:
    - expat 2.2.*
    - pango 1.40.*
    - proj4 4.9.3
    - eccodes
    - python
    - numpy >=1.8
    - simplejson
    - libnetcdf
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX magics  # [not win]
    - conda inspect objects -p $PREFIX magics  # [osx]
  imports:
    - Magics
    - Magics.macro
    - Magics.metgram
    - Magics.toolbox

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF's Meteorological plotting software

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
