{% set version = "4.0.0" %}

package:
  name: magics
  version: {{ version }}

source:
  fn: Magics-{{ version }}-Source.tar.gz
  url: https://confluence.ecmwf.int/download/attachments/3473464/Magics-{{ version }}-Source.tar.gz?api=v2
  sha256: 3628063666859737948ed463de8e03300432b6f68a16e616a0c5e4c3387da5ee

build:
  number: 1005
  skip: True  # [(win and vc<14)]
  detect_binary_files_with_prefix: true
  features:
    - vc14  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # the CDTs below are needed when building with Metview enabled
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - m2-unzip  # [win]
  host:
    - python
    - pip
    - wheel
    - pkg-config  # [not win]
    - boost
    - expat
    - glib  # [not win]
    - pango  # [not win]
    - cairo  # [not win]
    - proj4
    - eccodes
    - libnetcdf
    - pthreads-win32  # [win]
    - libiconv  # [win]
    - jinja2
    - qt  # [not win]
    - zlib
  run:
    - python
    - numpy
    - expat
    - pango  # [not win]
    - cairo  # [not win]
    - proj4
    - eccodes
    - simplejson
    - libnetcdf
    - pthreads-win32  # [win]
    - libiconv  # [win]
    - qt  # [not win]
    - zlib

test:
  requires:
    # the CDTs below are needed when building with Metview enabled
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
  commands:
    - conda inspect linkages -p $PREFIX magics  # [not win]
    - conda inspect objects -p $PREFIX magics  # [osx]
    - printf "%s\n" "${MAGPLUS_HOME:?MAGPLUS_HOME is not set"  # [not win]
    - set | grep "MAGPLUS_HOME"  # [win]
  imports:
    - Magics  # [not linux]
    - Magics.macro  # [not linux]
    - Magics.metgram  # [not linux]
    - Magics.toolbox  # [not linux]

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF's Meteorological plotting software

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
    - dtip
