{% set name = "Magics" %}
{% set version = "4.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3473464/{{ name }}-{{ version }}-Source.tar.gz
  sha256: 1ab56519f1ea30d4f86e49cb46e472d7eae0a8e28ea462e305c07046630e565e
  patches:

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - m2-unzip  # [win]
  host:
    - pkg-config  # [not win]
    - expat
    - glib  # [not win]
    - pango  # [not win]
    - cairo  # [not win]
    - proj
    - eccodes >=2.21.0
    - libnetcdf
    - pthreads-win32  # [win]
    - libiconv  # [win]
    - zlib
    - magics-python
  run:
    - expat
    - pango  # [not win]
    - cairo  # [not win]
    - proj
    - eccodes >=2.21.0
    - simplejson
    - libnetcdf
    - pthreads-win32  # [win]
    - libiconv  # [win]
    - zlib
    - magics-python
  run_constrained:
    # magics is incompatible with magics-metview
    - magics-metview ==9999999999

test:
  commands:
    - printf "%s\n" "${MAGPLUS_HOME:?MAGPLUS_HOME is not set}"  # [not win]
    # disabled windows test since we don't have grep installed
    #- set | grep "MAGPLUS_HOME"  # [win]
  imports:
    - Magics
    - Magics.macro
    - Magics.metgram
    - Magics.toolbox

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache-2.0
  license_file:
    - LICENSE_for_source_files
    - COPYING
    - LICENSE

  license_family: Apache
  summary: ECMWF's Meteorological plotting software.

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
    - dtip
    - iainrussell
