{% set version = "3.1.0" %}

package:
  name: magics
  version: {{ version }}

source:
  fn: Magics-{{ version }}-Source.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473464/Magics-{{ version }}-Source.tar.gz
  sha256: c5c1cf1d1c06982927a40b61245b656ea8cadabe00201418bc69ccbe4156d658

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake 3.1.*
    - swig
    - pkgconfig
    - boost 1.64.*
    - expat 2.2.*
    - glib
    - pango 1.40.*
    - proj4 4.9.3
    - python-eccodes
    - python
    - jinja2
    - numpy 1.8.*
    - libnetcdf
  run:
    - expat 2.2.*
    - pango 1.40.*
    - proj4 4.9.3
    - python-eccodes
    - python
    - numpy >=1.8
    - simplejson
    - jinja2
    - libnetcdf

test:
  commands:
    - conda inspect linkages -p $PREFIX magics  # [not win]
    - conda inspect objects -p $PREFIX magics  # [osx]
  imports:
    - Magics
    - Magics.macro
    - Magics.metgram
    - Magics.toolbox

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF's Meteorological plotting software

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
