{% set version = "3.2.2" %}

package:
  name: magics
  version: {{ version }}

source:
  fn: Magics-{{ version }}-Source.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473464/Magics-{{ version }}-Source.tar.gz
  sha256: c70c6ffbb9b1b946266327e16851b9f708df185a4509066d9e193012f924334a

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - pkg-config
    - expat 
    - glib
    - pango
    - proj4
    - eccodes
    - python
    - numpy 
    - jinja2
    - libnetcdf
    - boost
    - libpng
  run:
    - expat 
    - pango 
    - proj4
    - eccodes
    - python
    - numpy 
    - simplejson
    - libnetcdf

test:
  commands:
    - conda inspect linkages -p $PREFIX magics  # [not win]
    - conda inspect objects -p $PREFIX magics  # [osx]
  imports:
    - Magics
    - Magics.macro
    - Magics.metgram
    - Magics.toolbox

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF's Meteorological plotting software

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
