{% set version = "3.4.0.10" %}

package:
  name: magics
  version: {{ version }}

source:
  fn: Magics-{{ version }}-Source.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/121845745/Magics-{{ version }}-Source.tar.gz
  sha256: 7637fc02342b7a8ecf6c974486bd2dbfee37ddb64c12bef714d5079907edbf9a

build:
  number: 1002
  skip: True  # [win and vc<14]
  detect_binary_files_with_prefix: true
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - m2-unzip  # [win]
  host:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - pkg-config  # [not win]
    - boost
    - expat
    - glib  # [not win]
    - pango  # [not win]
    - proj4
    - eccodes
    - perl  # [not win]
    - perl-xml-parser  # [not win]
    - m2-perl  # [win]
    - libnetcdf
    - pthreads-win32  # [win]
    - libiconv  # [win]
    - jinja2
  run:
    - expat
    - pango  # [not win]
    - proj4
    - eccodes
    - simplejson  # [not win]
    - libnetcdf
    - pthreads-win32  # [win]
    - libiconv  # [win]

test:
  commands:
    - conda inspect linkages -p $PREFIX magics  # [not win]
    - conda inspect objects -p $PREFIX magics  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF's Meteorological plotting software

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
