# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eRgknU9Tnni8N86vj6UfrMlLbz+FPtFrh36s2ZSEcFv31pbHr/gcAlYOqXLOpVkv0HTMerxlvCvUCXtEsJ1kVHB6mZBmH+/YY2D9dzOrSE37qKcMZssjGpC62rNL59lay/SS7Ek3yyDxm8AToLiZLP5eDAUzQgVNBYD/XrbpipaIhtu7nTv8EmQA9o0WiN0ZSque41WhnZ0FehYiHlMM/hX/klJKs7nwV8WFAnaQzqIG0SkpNdDyU+FYviKNzdZEgrbUcgMb9A/fWUqWbnI5hLZu/gKHoB6TRJT43F9mD2MRPW1bcHze25lFtmfSW0sI7nSGjwrjIlmsScn8GklUvZKJlm8rZN/9usGIrT3jBv0dIgMHWYYkClw1e6Kb/quVDlMZ8E2gdbyf8sMuc46eVMjjbUZUeu5mxQAmBkwAKyvaSt0RwLWAfvMAbC9u+kR45fPOwMxMWs+Y/fCWRYJHx/nFkKSWzT7eKQ4y03w81ZjnFipg2QK5hors1AaM4lJZTnSa7rHayw0oOSag3ZB666fNovno5nF54oLE5WKq7AmZ2O23lWYtOeYVFEbVG5ZV7J6n40zN2gXp5HemnQJ9Oypf81nXfLeTtoaQIRthiZzHwYnBcPNOLvxg6Sb/yrUDOnLlBmm9fyjJzl7pLlaEoXn++6qfSFD1cx0Y9N35Rm8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
