appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: V8prSQAEgw4etRFizesTD5x5cAtF3gUC7gtHp/98jJ7eIhTd+AL9wfmyHYzvHsrt81hXji+oi5ayvcnvH3lLKuBSwwJSFfPGzoEM4enddtKYYkcgw9ak3c5B5+WmN5r0eGtJ/V5yMJXlEJEznZkYcez7O0Tkqsg+cHZ3dyJlFzMTtNoAgQTJip2+URg68rKjp4fYC8KVd95i5smtG7UoSwh9uEUFv1u0F2a94dSBcP9NxdyD0YIUubcfm8asMCwgWIfn8Cp1R41JnwBsO6yP7gzW6RBqAqvILgYOr2i5IBNbFIpYFnHRbUopt0n3njpnemvy5H2w1POYVsCJ33w/lIE+i1fd40qGfcSbg8hJI4hDgXfvu/96Xypym6Jr+0qXEDOC7aMY7HQZ4Ts48SnSK4VlOT9D2KGYyWrJQFu7Wy+JEcQUxJcWOGUPa6KW8ES0YmEP7RepYUqVWg3EEGPwE4I3WtRmbjuxPhaYpUsPgs1iyrnV80m+B9tm5byoQs3CKBdmvaDueEoK1K59clnBcQbj7KCNhin298Lx0Qx2IHJf6w10pxgdYYHwnDyRoaur8xWpIki6caPwaNKin2tgfSkrK03wmeACJvUT5KRfrck/vgFERtNtFA1ceDyy8wjdQjI1ZzHaJg2Hpf81JL/yXOsi4Jop+AoBH/du9FEbGZw=}
