azure:
  settings_win:
    pool:
      vmImage: windows-2019
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux: azure
  osx: azure
  win: azure
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
